events.cesium.kafka.delay.producer.DestinationKafkaProducer:
    Topic:
        test-delay-destination
    KafkaConfig:
        bootstrap.servers: localhost:9092

events.cesium.kafka.delay.consumer.SourceKafkaConsumer:
    Topic:
         test-delay-source
    KafkaConfig:
        bootstrap.servers: localhost:9092
        group.id: delay-consumer-group

events.cesium.kafka.delay.producer.TrackerKafkaProducer:
    Topic:
        delay-tracker
    KafkaConfig:
        bootstrap.servers: localhost:9092

events.cesium.kafka.delay.consumer.TrackerKafkaConsumer:
    Topic:
         delay-tracker
    KafkaConfig:
        bootstrap.servers: localhost:9092
        group.id: delay-consumer-group
