events.cesium.kafka.delay.producer.DelayProducer:
    Topic:
        test-delay-output
    KafkaConfig:
        bootstrap.servers: 127.0.0.1:9092

events.cesium.kafka.delay.consumer.DelayConsumer:
    Topic:
         test-delay-input
    KafkaConfig:
        bootstrap.servers: 127.0.0.1:9092
        group.id: delay-consumer-group

events.cesium.kafka.delay.consumer.DelaySeekConsumer:
    Topic:
         test-delay-input
    KafkaConfig:
        bootstrap.servers: 127.0.0.1:9092

events.cesium.kafka.delay.producer.DelayTrackerProducer:
    Topic:
        delay-tracker
    KafkaConfig:
        bootstrap.servers: 127.0.0.1:9092

events.cesium.kafka.delay.consumer.DelayTrackerConsumer:
    Topic:
         delay-tracker
    KafkaConfig:
        bootstrap.servers: 127.0.0.1:9092
        group.id: delay-consumer-group

events.cesium.kafka.delay.consumer.DelayTrackerRebalanceConsumer:
    Topic:
         delay-tracker
    KafkaConfig:
        bootstrap.servers: 127.0.0.1:9092
        